### ISSUE TITLE
coverage information

### ISSUE THREAD

**Issue by colindaven** [mmpust/raspir#3]
Hi Marie,

I'm using a human + bacterial reference and getting coverage info for human, which I don't need later. It's big too, 5GB.

    samtools depth ${fname}.sorted.bam > ${fname}.sorted.raspir1.csv

I can't see any reference or code for excluding this. I'll filter it out and will propose some changes to you soon.

Colin

**Comment by mmpust** [comment]
Hey Colin,

human reads will be automatically removed in the first step of raspir and not during the initial preparation step. I do agree that this is computationally inefficient and it makes sense to do this during the early preparation phase.

I am at the moment writing a script to directly combine raspir with the Wochenende pipeline (and KrakenUniq), this will hopefully reduce the overall computational cost as well because we already have the filtered and clean BAM files and do not need to re-create them for raspir. Nonetheless, I am very much looking forward to getting your feedback! Thank you, Colin!

Marie
