### ISSUE TITLE
A couple of questions about raspir

### ISSUE THREAD

**Issue by MrOlm** [mmpust/raspir#6]
Hello,

Congratulations on the recent publication! This seems like a very useful and much needed tool in the field of metagenomics. After a quick reading the pub I just have a couple of questions:

1) Are circular genomes required to run raspier, or can draft quality genomes in a couple of pieces be used as input?

2) Has any testing been done on real metagenomes with subsetting? E.g. take a deeply sequenced human gut metagenome, identify all known species, subset that metagenome by 10x, run raspir, see how the identified species compare. I understand that there was in silico testing performed, but real metagenomes often have weird oddities / strain heterogeneity / etc. to them that is difficult to account for with is silico benchmarking.

Thanks in advance and congrats again,
Matt

**Comment by mmpust** [comment]
Dear Matt,

Thank you very much indeed! 

You asked two very good questions:
1. At the moment, a circular bacterial genome is a prerequisite for the tool. The reason for this is that usually, the discrete Fourier transform treats the position domain and the frequency domain signal as periodic functions. If we have a circular genome, we can rotate along the circle endlessly long and the generated time-domain signal of each rotation will perfectly fit into a single period. If we try to force a non-periodic linear or highly fragmented chromosome with fixed endpoints into a discrete periodic frequency spectrum, the ends of the spectrum may extend into the following periods and distort the overall signal, because a linear construct cannot be directly integrated. In theory, it is possible to get the Fourier transform of read position combinations from linear chromosomes by convolving their time-domain signals with appropriate sinc functions. This is currently not addressed by the tool but further updates are planned.
But you may agree that when we investigate the human respiratory tract or the skin microbiome, we often know the common microbes and pathogens of the particular habitat, they mostly have circular genomes and for the majority of these bacterial species, high-quality reference genomes are available. As a consequence, the approach is applicable. If we however investigate unknown habitats, we may find novel yet-uncultured bacteria. In this case, the tool runs up against its limits yet. However, for unknown environments, we generally rely on _de novo_ assemblies and not reference-based alignment because the reference database will not cover the newly identified organisms. 

2. This is a very smart way to further validate the use of Fourier transforms for species identification! This has not yet been done but I will consider it, thank you! I completely agree with you that real-world datasets introduce a wide range of challenging situations, including strain heterogeneity but also variations in growth rates so that we have a gradient of reads from origin to terminus. This growth rate problem may not be that important for the rare species since they are probably not growing extensively but it may still affect the final interpretation. The recent publication is a _Brief Communication_ and not a full research article because of this exact limitation. We decided to focus on highly-controlled _in-silico_ simulations to demonstrate the power of Fourier transforms and we made the _in-silico_ community as challenging as possible, by choosing the critical species, which are genetically highly similar (_Streptococcus_ spp.) and are known to be difficult to be differentiated on species level from other database entries (_Escherichia coli_ vs _Shigella_ spp.). In the last part of the publication, we applied the tool to real-world sequencing data of human placenta samples and were able to verify the absence of microbial communities in this particular habitat. We just constantly detected the _Ralstonia_ spp. which is known to grow and form biofilms in ultra-pure pharmaceutical solutions. This finding was independent of sequencing depth and the number of Ralstonia-specific reads. 

Currently, we are validating the tool on further real-world datasets obtained from various environments with known microbial community composition and abundances. The first results show that the approach is not yet able to solve all challenging taxonomic classification situations, but it always leads to a significant decline in false discovery and omission rates. I am going to communicate the results and recommendations here as soon as the next testing phase has ended. 

Kind regards,
Marie

**Comment by MrOlm** [comment]
Wonderful- thank you for the very thorough reply. This all makes complete sense.

Thanks and congrats again,
Matt
