### ISSUE TITLE
archaea are microbes too

### ISSUE THREAD

**Issue by nick-youngblut** [mmpust/raspir#8]
Any plans on creating a reference database of bacteria and archaea? 

If no, can you please provide the details on how you constructed the bacterial reference database? I can't find any info on that in the main manuscript, supplemental, or in the README of this repo.

I'm guessing that you did something like `ncbi-genome-download --formats fasta --assembly-levels complete bacteria`, but I just want to follow the exact same approach for archaea so that I can create a database of compete bacterial & archaeal genomes.

**Comment by mmpust** [comment]
Dear Nick,
you are absolutely right that archaea are microbes too and they are an extremely underestimated part of the human microbiome. I will provide a database containing bacteria and archaea reference genomes as soon as possible. Unfortunately, I cannot share all the scripts with you for generating and cleaning the reference database since some of them are in the publication process and I am not the main author of these scripts. 

Yes, basically we downloaded all the completely sequenced reference-genomes of bacteria from NCBI and then further curated it to remove genomes that are contaminated with barcode sequences or contain the word "complete" in the description but are assembled draft genomes in reality. We also kept just one strain per species and this strain was randomly selected. At the moment, we are testing raspir on pangenome databases, since the choice of the reference database is known to influence the final outcome significantly. This has just recently reported again by the group of Fernando González-Candelas, see https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1008678

If you need the database immediately, you may just take the bacterial reference database that we provided and append your completely sequenced archaeal genomes manually. 
Kind regards,
Marie

**Comment by nick-youngblut** [comment]
Thanks for the info! I'm working on adding archaeal genomes to your bacterial database using the following basic approach:

* ncbi-genome-download --formats fasta --assembly-levels complete archaea
* checkm + drep
  * 95% ANI
  * >= 90% completeness
  * < 5 contamination
* seqkit
  * to make sure the "complete" genomes are actually complete

Did you include plasmids, if they were included in the genomes? What about non-circular genomes such as in Vibrio?

**Comment by nick-youngblut** [comment]
Is there an issue with space in the fasta names? The bacterial genome seq names don't have any spaces, but do have non-standard characters (eg., `[`, `+`, and `'`). A few of the seq names:

```
>1_AE009952_1_Yersinia_pestis_KIM10+
>1_CP000777_1_Leptospira_biflexa_serovar_Patoc_'Patoc_1__Ames_'_I
>1_CP001104_1_[Eubacterium]_eligens_ATCC_27750
```

**Comment by mmpust** [comment]
Hello Nick,
1. Did you receive any error messages because of the non-standard characters? 
2. What do you mean by "plasmids included in the genomes"?
3. To my knowledge _Vibrio_ spp. have circular genomes ... or to what do you refer to?

Kind regards,
Marie

**Comment by nick-youngblut** [comment]
1. I had not, but I didn't know if raspir requires BAM files with specifically formatted subject IDs (sequence names in the reference genome fasta)
2. Many complete genomes include >=1 plasmid. For instance, ~1/4 of the "complete" archaeal genomes that I am planning on adding to your bacterial genome database include >=1 plasmid. Did you remove those from the "complete" bacterial genomes in your database?
3. For example, certain Vibrio species have 2 linear chromosomes (See Figure 1 of [Shapiro et al., 2012](https://science.sciencemag.org/content/336/6077/48/tab-pdf) for an example)). Vibrio is not the only example bacteria having multiple (linear) chromosomes.

**Comment by mmpust** [comment]
Dear Nick,
I see, thank you for your clarification!

1. For raspir runs, spaces in the headers should be replaced by underscores but special characters should not cause any problems.
2. Plasmids should be separately submitted to the NCBI database. They are indeed downloaded with the "complete bacteria" but they should not be incorporated into the genome. If this is the case, it does not seem to be a high-quality reference genome. 
3. The Fourier transforms have not been tested on linear chromosomes (see Supplementary Text 1). Linear constructs should be avoided or if alignments occur you should manually evaluate the read distribution. To my knowledge, most of the human-associated _Vibrio_ spp, including _Vibrio cholerae_ and _Vibrio fluvialis_ have circular genomes. For many other environmental _Vibrio_ spp. including the _Vibrio cyclitrophicus_ (mentioned in your cited article from 2012), only highly assembled draft genomes were available for a long period of time. They also seem to be circular with entries from 2021 (see https://www.ncbi.nlm.nih.gov/nuccore/NZ_CP039700.1), even though they have not been circularised in 2012. I would avoid draft genomes with raspir. However, if you have multiple circular chromosomes of one organism, you may just randomly select one or keep both for the run evaluation. 

Kind regards,
Marie

**Comment by nick-youngblut** [comment]
> but special characters should not cause any problem

The sequence headers cannot contain commas; otherwise, `pd.read_csv(inF, delimiter=',')` in `raspir_v1_0_unix.py` fails.

**Comment by mmpust** [comment]
Dear Nick,
there are several ways to remove the commas from your reference database

**Python**
1. Create a python file and name it "remove_special_characters_in_refdb.py" (the script has been added to the main branch)
2. In the line "f2.write" adjust what special characters you would like to have replaced or add more characters.
3.  Give your input file (.FASTA format) as the first argument and the name of your output file as the second argument
```
#!/bin/python

import sys

if len(sys.argv) != 3:
    print("USAGE: emove_special_characters_in_refdb.py <input.fa> <output.fa>")
    sys.exit(1)

with open(sys.argv[1], "r") as input_fasta, open(sys.argv[2], "w") as output_fasta:
        for line in input_fasta:
                if not line.strip():
                        continue
                output_fasta.write(line.replace(".", "_").replace(" ", "_").replace(",", "_"))
```

For a quick replacement of individual special characters,  **tr** or **sed** one-liners should also do the trick. 
```
tr ',' '_' < input.fa > output.fa
sed 's/,/_/g' input.fa > output.fa
```

If you have any further questions, you are welcome to open a new comment and/or send me a test sample causing the problem.  This will make it easier for me to look into the issue.

Kind regards,
Marie

**Comment by nick-youngblut** [comment]
Thanks for the quick response. I should have noted that my comment about commas was a warning to any user that read this issue thread. It could be helpful to include such a warning in the README under the "Set-up the reference database" section.

**Comment by nick-youngblut** [comment]
I found out the hard way that the naming of the reference database contigs really matters for the final output, given that the raspir workflow extracts the species names from the contig IDs. For instance  "Clostridium perfringens" is extracted from the contig name ">1_BA000016_3_Clostridium_perfringens_13_DNA".

When I created a database of bacteria and archaea, I got archaeal "species" names in the final output that look like the following:

```
strain SM9
YE315
M1
```

...because I didn't know that the contig names MUST be formatted as `1_<accession>_<genus>_<species>_[...]`.

How about added a mapping file that maps the taxonomy to the contigs? This allows for a more flexible taxonomy, such as including the entire lineage (and taxid) instead of just the binomial species name. raspir can map the contig IDs to the species names (the "organism") after loading the read mapping info.

**Comment by mmpust** [comment]
Dear Nick,
thank you very much for all your suggestions and improvements! This is very much appreciated and will hopefully help other users who want to test raspir on their own databases, thanks! 

For a quick and dirty fix,  I just changed the source code so that it prints the entire header now instead of cutting it into pieces.
I just tested it on two test datasets and it does work in both ways for the bacteria. You may find the script in the main folder raspir_with_customised_refdb/

If it is not working with your reference genomes, can you provide me with the NCBI identifiers. However, a mapping file as you have suggested is the most appropriate solution. 

Kind regards, 
Marie

**Comment by nick-youngblut** [comment]
Thanks for the quick response! The quick and dirty fix (i.e., not splitting by `sep = "_"`) works. 

A major upside of the contig-name mapping file would be that the user could include the entire lineage info and/or taxid, as is standard in other metagenome profiling software such as Kraken2.

**Comment by mmpust** [comment]
Thanks, Nick! I will include the mapping file in the next update.

**Comment by nick-youngblut** [comment]
Any updates on adding archaea to the default reference database?

**Comment by mmpust** [comment]
Dear Nick, 
Unfortunately, there are no updates on adding archaea to the reference database yet and I cannot give you a fixed timetable when we will be able to add archaeal reference genomes plus testing the suitability of the tool in predicting their presence/absence. Any updates from your side so far? 
Best wishes,
Marie
